/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as ItemsNewRouteImport } from './routes/items/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/people': typeof PeopleRoute
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/people': typeof PeopleRoute
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/people': typeof PeopleRoute
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/health'
    | '/people'
    | '/sign-in'
    | '/items/$id'
    | '/items/new'
    | '/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/health'
    | '/people'
    | '/sign-in'
    | '/items/$id'
    | '/items/new'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/health'
    | '/people'
    | '/sign-in'
    | '/items/$id'
    | '/items/new'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HealthRoute: typeof HealthRoute
  PeopleRoute: typeof PeopleRoute
  SignInRoute: typeof SignInRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsNewRoute: typeof ItemsNewRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HealthRoute: HealthRoute,
  PeopleRoute: PeopleRoute,
  SignInRoute: SignInRoute,
  ItemsIdRoute: ItemsIdRoute,
  ItemsNewRoute: ItemsNewRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
