// Every string a person can read. The app is English, and stays English until
// someone adds a second file beside this one — at which point nothing in the
// screens has to change, because no screen holds a sentence of its own.
//
// A value is either a sentence, or one sentence per plural form. `{name}` in a
// sentence is filled in by t(); see i18n.ts.
export const en = {
  'app.name': 'InHouse',
  'app.tagline': 'A private system for a team that knows each other.',

  'nav.home': 'Home',
  'nav.items': 'Items',
  'nav.people': 'People',
  'nav.health': 'Health',
  'nav.account': 'Account',
  'nav.primary': 'Primary',

  'action.save': 'Save',
  'action.saving': 'Saving…',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'action.edit': 'Edit',
  'action.retry': 'Try again',
  'action.refresh': 'Refresh',
  'action.refreshing': 'Refreshing',
  'action.refreshed': 'Updated',
  'action.showMore': 'Show more',
  'action.loadingMore': 'Loading more…',
  'action.signOut': 'Sign out',
  'action.back': 'Back',
  'action.clear': 'Clear',
  'action.update': 'Update',

  'theme.label': 'Appearance',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.system': 'Follow the system',
  'theme.toggle': 'Switch between light and dark',

  'update.ready': 'A new version is ready',
  'update.body': 'Your work is saved; updating takes a moment.',

  'error.title': 'This screen could not be shown',
  'error.body': 'The last thing tried did not work. Try again, or go home.',
  'error.notFoundTitle': 'There is nothing at this address',
  'error.notFoundBody': 'The link may be old, or the record may be gone.',
  'error.offline': 'The server did not answer. Check the connection.',
  'error.requestId': 'Reference {id}',

  'signIn.title': 'Sign in',
  'signIn.intro': 'This app is for invited people only.',
  'signIn.email': 'Email',
  'signIn.sendLink': 'Send me a link',
  'signIn.sending': 'Sending…',
  'signIn.sentTitle': 'Check your email',
  'signIn.sentBody': 'A link to sign in is on its way to {email}. It works once, and for an hour.',
  'signIn.usePassword': 'Use a password instead',
  'signIn.useLink': 'Use a link instead',
  'signIn.password': 'Password',
  'signIn.submit': 'Sign in',
  'signIn.failed': 'That did not work. Check the address and try again.',

  'home.title': 'Home',
  'home.description': 'What is open, what is late, and what moved this week.',
  'home.open': 'Open',
  'home.overdue': 'Overdue',
  'home.doneWeek': 'Done in the last 7 days',
  'home.openNote': 'Everything not yet finished',
  'home.overdueNote': 'Past its due day and still open',
  'home.doneWeekNote': 'Finished since {date}',
  'home.finishedByWeek': 'Finished, by week',
  'home.recent': 'Recent changes',
  'home.recentEmpty': 'Nothing has changed yet',
  'home.recentEmptyBody': 'Changes people make show up here as they happen.',

  'items.title': 'Items',
  'items.description': 'The worked example this kit ships with. Rename it, or delete it.',
  'items.new': 'New item',
  'items.search': 'Search',
  'items.searchPlaceholder': 'Title or notes',
  'items.status': 'Status',
  'items.due': 'Due',
  'items.assignee': 'Assigned to',
  'items.anyStatus': 'Any status',
  'items.anyDue': 'Any day',
  'items.anyone': 'Anyone',
  'items.unassigned': 'Nobody',
  'items.dueOverdue': 'Overdue',
  'items.dueWeek': 'Within a week',
  'items.dueNone': 'No due day',
  'items.statusOpen': 'Open',
  'items.statusDone': 'Done',
  'items.count': { one: '{count} item', other: '{count} items' },
  'items.emptyTitle': 'No items yet',
  'items.emptyBody': 'The first one takes a title and nothing else.',
  'items.emptyFiltered': 'Nothing matches these filters',
  'items.emptyFilteredBody': 'Widen the search, or clear the filters.',
  'items.notes': 'Notes',
  'items.title.label': 'Title',
  'items.titlePlaceholder': 'What needs doing',
  'items.notesPlaceholder': 'Anything worth remembering',
  'items.dueOn': 'Due day',
  'items.created': 'Added {when}',
  'items.saved': 'Saved',
  'items.deleted': 'Deleted',
  'items.deleteTitle': 'Delete this item?',
  'items.deleteBody': 'It goes from every list. The change stays in the history.',
  'items.history': 'History',
  'items.historyEmpty': 'Nothing has changed since this was added.',
  'items.attachments': 'Attachments',
  'items.attachmentsEmpty': 'No files yet.',
  'items.addFile': 'Add a file',
  'items.newTitle': 'New item',
  'items.newDescription': 'A title is all that is needed; the rest can wait.',

  'people.title': 'People',
  'people.description': 'Who can sign in, and what each of them may do.',
  'people.invite': 'Invite someone',
  'people.inviteTitle': 'Invite someone',
  'people.inviteBody': 'They get an email with a link that signs them in.',
  'people.name': 'Name',
  'people.email': 'Email',
  'people.role': 'Role',
  'people.lastSeen': 'Last seen',
  'people.never': 'Never',
  'people.deactivate': 'Deactivate',
  'people.activate': 'Activate',
  'people.inactive': 'Inactive',
  'people.sent': 'The invitation is on its way to {email}.',
  'people.emptyTitle': 'Only you so far',
  'people.emptyBody': 'Invite the people who need to see this.',

  'role.owner': 'Owner',
  'role.member': 'Member',
  'role.viewer': 'Viewer',

  'health.title': 'Health',
  'health.description': 'What is wrong, and nothing else.',
  'health.allWell': 'Everything is fine.',
  'health.problems': 'Needs attention',
  'health.jobs': 'Scheduled work',
  'health.jobName': 'Job',
  'health.queued': '{count} queued',
  'health.running': '{count} running',
  'health.failed': '{count} failed in 24 h',
  'health.lastRun': 'Last finished',
  'health.recentErrors': 'Errors in the last 24 hours',
  'health.noErrors': 'No errors recorded.',
  'health.disk': 'Disk',
  'health.diskUsed': 'Used',
  'health.diskFreeLabel': 'Free',
  'health.diskFree': '{free} free of {total}',
  'health.backup': 'Last backup',
  'health.release': 'Release',
  'health.database': 'Database',
  'health.startedAt': 'Running since',
  'health.never': 'Never',
  'health.occurrences': { one: 'once', other: '{count} times' },

  'account.title': 'Account',
  'account.description': 'Your name, and how this app looks to you.',
  'account.yourName': 'Your name',
  'account.saved': 'Saved',
  'account.timeZone': 'Time zone',
  'account.timeZoneNote': 'The app has one time zone for everyone: {zone}.',

  'history.changed': '{actor} changed {field} from {from} to {to}',
  'history.set': '{actor} set {field} to {to}',
  'history.cleared': '{actor} cleared {field}',
  'history.created': '{actor} added this',
  'history.deleted': '{actor} deleted this',
  'history.restored': '{actor} restored this',
  'history.someone': 'Someone',
  'history.empty': '(empty)',

  'form.required': 'This cannot be empty',
  'form.invalidEmail': 'That is not an email address',

  'list.loading': 'Loading',
  'list.showingOf': 'Showing {shown} of {total}',
} as const;

export type Strings = typeof en;
